# Generated by Django 4.2.2 on 2024-08-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='', width_field='image_width')),
                ('url', models.URLField()),
                ('views', models.PositiveBigIntegerField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
