# Generated by Django 4.2.2 on 2024-08-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaylistMaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_info',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
